name: Build job

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/*'
      - '.github/ISSUE_TEMPLATE/**'
      - '*.yml'
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/*'
      - '.github/ISSUE_TEMPLATE/**'
      - '*.yml'
      - 'README.md'

jobs:
  build:
    name: windows-latest Release
    runs-on: windows-latest

    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Ensure NuGet Source
        uses: fabriciomurta/ensure-nuget-source@v1
      - name: Get git short hash
        id: git_short_hash
        run: echo "::set-output name=result::$(git rev-parse --short "${{ github.sha }}")"
      - name: Clear
        run: dotnet clean && dotnet nuget locals all --clear
      - name: Build
        run: dotnet build -c "Release" /p:Version="1.0.0" /p:SourceRevisionId="${{ steps.git_short_hash.outputs.result }}" /p:ExtraDefineConstants=DISABLE_UPDATER
      - name: Test
        run: dotnet test -c "Release"
      - name: Publish
        run: dotnet publish -c "Release" -r "win-x64" -o ./publish /p:Version="1.0.0" /p:SourceRevisionId="${{ steps.git_short_hash.outputs.result }}" /p:ExtraDefineConstants=DISABLE_UPDATER Ryujinx
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ryujinx-Release-1.0.0+${{ steps.git_short_hash.outputs.result }}-win_x64
          path: publish